export const INCREMENT = "INCREMENT_COUNTER"
export const DECREMENT = "DECREMENT_COUNTER"

export const GET_DOCTOR = "GET_DOCTOR"
export const POST_DOCTOR = "POST_DOCTOR"
export const DELETE_DOCTOR = "DELETE_DOCTOR"
export const UPDATE_DOCTOR = "UPDATE_DOCTOR"


export const GET_PRODUCT = "GET_PRODUCT"
export const POST_PRODUCT = "POST_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"


export const LOADING_MEDICINES = "LOADING_MEDICINES"
export const ERROR_MEDICINES = "ERROR_MEDICINES"


export const ADD_CART = "ADD_CART"
export const GET_CART = "GET_CART"
export const DELETE_CART = "DELETE_CART"
